version: "3"
services:
  db:
    image: mysql:8.0.22
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "ApiDB"
      MYSQL_USER: 'ajh'
      MYSQL_PASSWORD: '1234'