version: "3.9"
services:
  mysql:
    image: mysql:8.0.22
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ApiDB
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
    networks:
      - example

  application:
    build: .
    container_name: spring-container
    ports:
      - "9000:9000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - example
#    restart: always
networks:
  example:
    driver: bridge