#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#    url: jdbc:h2:mem:testdb
spring:
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/ApiDB
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

#  h2:
#    console:
#      enabled: true

server:
  port: 9001


#version: '3.2'
#
#services:
#  mysql:
#    image: mysql:8.0.31-debian
#    command: --default-authentication-plugin=mysql_native_password
#    environment:
#      MYSQL_ROOT_PASSWORD: "1234"
#      MYSQL_USER: 'ajh'
#      MYSQL_PASSWORD: '1234'
#    ports:
#      - '3306:3306'
#    volumes:
#logging:
#  config: classpath:logback.xml
#      - ./mysql:/etc/mysql