spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true

server:
  port: 9191